name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Docker Login             
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker images              
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            niccolas1987/review-filmes:v${{ github.run_number }}
            niccolas1987/review-filmes:latest
                
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name eks-aula

      - name: Deploy to Kubernetes cluster              
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./k8s/deployment.yml
          images: |
            niccolas1987/review-filmes:v${{ github.run_number }}
