name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Docker Login             
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        run: echo "Construir a imagem da aplicação"
      
      - name: Passo 2
        run: echo "Publicar a imagem no Docker Hub"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 1
        run: echo "Deploy da aplicação"
